for You
goldentrash/23-24_study_2nd_java-lotto-6 pull request #1
Opened 2024-05-22 10:45 UTC by goldentrash

thx :)

2024-05-26 07:06 UTC, pjy1368 requested changes

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/Application.java
> +  public static <T> T tillSuccess(Supplier<T> func) {
till은 좀더 캐쥬얼한 상황에서 쓰고 until은 공식적인 상황에서 쓰이는 어감이라고 나와있는데, 개인적으로 후자로 표현하면 좋을 듯싶네요.
https://byjus.com/english/difference-between-till-and-until/

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +  }
도메인에 입출력 로직이 혼재되어 있으면 어떠한 단점이 있을까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +    return new Money(sources.stream().map((other) -> other.value).reduce(0, Integer::sum));
stream()은 일반적으로 아래와 같이 쓰는 편인데 어떻게 생각하시나요?
```java
sources.stream()
    .map()
    .reduce();
```

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +  }
gte가 무슨 뜻인가요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +      throw new IllegalArgumentException("[ERROR] 금액 단위는 1,000원입니다.");
예외 메시지의 1,000원도 기존의 정의한 상수를 활용하면 좋을 것 같아요.

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Payment.java
> +  private static final Money MIN_AMOUNT = new Money(1_000);
Money에 1000 상수가 이미 정의되어있는데, 그것을 활용해보거나 MIN_AMOUNT를 Money 객체로부터 받으면 어떨까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Payment.java
> +  private final List<Lotto> lottery;
lottery는 단수일 것 같은데 lotteries로 바꾸면 어떨까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Payment.java
> +  }
ditto (이전 리뷰와 동일하다는 뜻)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Payment.java
> +  }
toString()을 단순 로깅 용도가 아닌 출력 뷰 로직으로 사용하면 어떠한 문제점이 있을까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Payment.java
> +      throw new IllegalArgumentException("[ERROR] 최소 주문 금액은 1000원입니다.");
여기도 1000 상수가 Money에 박혀있는데 이곳저곳에서 1000을 쓰기보다는 하나의 상수를 잘 활용했으면 합니다.

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/WinningNumbers.java
> +  }
ditto (도메인, 뷰 로직 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/WinningNumbers.java
> +      throw new IllegalArgumentException("[ERROR] 당첨 번호는 6개의 숫자로 이뤄져야 합니다.");
ditto (상수 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/WinningNumbers.java
> +  }
```java
this.numbers = numbers.stream()
                            .sorted()
                            .collect(Collectors.toList());
```
이렇게 작성하면 처음부터 정렬된 리스트를 가져올 수 있습니다.

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/WinningNumbers.java
> +  }
ccontains 표현이 더 좋아보이는데 overlap 사용하신 이유가 있나요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Lotto.java
> +  public static final Money PRICE = new Money(1_000);
ditto (상수 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Lotto.java
> +    Collections.sort(mutable);
ditto (정렬 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Lotto.java
> +    Collections.sort(mutable);
추가로, WinningNumbers와 Lotto 모두 lotto numbers 만드는 과정에서 중복 로직이 발생하는데 어떻게 해결할 수 있을까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Lotto.java
> +  }
ditto (WinningNumbers와 중복됨)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Result.java
> +  }
ditto (toString 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Prize.java
> +  }
ditto (toString 관련)

2024-05-26 07:06 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +  }
float로 하면 부동 소수점 이슈로 정확한 값이 나오지 않을텐데, 돈과 관련된 부분은 오차가 없어야 합니다. 어떻게 해야 할까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/test/java/lotto/domain/PaymentTest.java
> +    @DisplayName("`mock` 정보가 포함되어야 한다.")
mock 정보보다는 구체적으로 검증하려는 대상이 무엇인지 명시하는 것이 직관적이지 않을까요?

2024-05-26 07:06 UTC, pjy1368 commented on src/test/java/lotto/domain/ResultTest.java
> +    @DisplayName("`mock` 정보가 포함되어야 한다.")
ditto

2024-05-26 07:06 UTC, pjy1368 commented on src/test/java/lotto/domain/ResultTest.java
> +    @DisplayName("`mock` 정보가 포함되어야 한다.")
ditto

2024-05-26 07:50 UTC, goldentrash reviewed
Commit Message ㅎ... 다음부턴 제대로 쓰겠습니다. ><

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +  }
layered-architecture에서 **도메인은 비즈니스 로직**을 담당합니다. 보통 **입출력은 사용자 요구사항에 맞춰 변경이 빈번**할 수 있기 때문에 presentational layer로 분리합니다.

하지만 현 과제 수행을 위해 layer를 나누는 건 필요 이상으로 **코드 복잡도**를 높일 거라고 판단했습니다.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +    return new Money(sources.stream().map((other) -> other.value).reduce(0, Integer::sum));
확실히 별도 변수로 분리했으면 더 읽기 편했겠네요! (의도가 맞았을까요?)

```java
int totalAmount = sources.stream()
   .map(other::value)
   .reduce(0, Integer::sum));

return new Money(totalAmount);
```

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +  }
사실 이 부분은 함수 목적을 생각했을 때 **이름이 문제**네요.

돈의 수량을 나누는게 목적이 아니라, **지불 금액**과 **제품 가격**이 주어졌을 때, **몇 개의 제품이 지급되어야 하는지 판단**하기 위한 함수입니다.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +  }
부동 수소점과 관련해서 오차를 없애야 하는 상황이라면, **`fixed-point`로 변경하고 연산을 수행**해야 합니다. 이를 위한 별도 domain을 만들어보는 것도 재밌겠네요.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +  }
`greater than equal`입니다. 요즘 Latex를 자주 써서... ㅎㅎ

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Money.java
> +      throw new IllegalArgumentException("[ERROR] 금액 단위는 1,000원입니다.");
아 Error Msg를 일단 작성한 후, `String.format`으로 한 번에 수정했었는데... 누락된 부분이 생각보다 많네요.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Payment.java
> +  private static final Money MIN_AMOUNT = new Money(1_000);
최소 주문 금액은 `Payment`에서 정의해야 한다고 생각합니다.

추후 확장을 생각했을 때, 그리고 Domain의 역할을 생각했을 때, 최소 주문 금액은 자체로 가지고 있어야 한다고 생각합니다. **물품마다 최소 주문 금액이 다를 수 있으니까요**.

대신 `Money`의 `validate`를 보면 `0` 이상으로 **적절한 돈의 범위**는 별도로 정의해주고 있습니다.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Payment.java
> +  private final List<Lotto> lottery;
lottery... 단수...? 어째서...?

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Payment.java
> +  }
이 부분은 생각해 본 적이 없는데 정말 중요한 내용이네요.

확실히 단순 로깅 용도와 출력 뷰를 분리하는게 중요해 보입니다. 반성하게 되네요.

**로깅(`toString`)은 해당 객체를 식별할 수 있어야** 합니다. 하지만 출력 뷰는 전혀 별개의 내용으로 사용자가 원하는 정보일 뿐이니까요.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/WinningNumbers.java
> +  }
`Stream`에 `sorted`가 있는 걸 몰랐네요. 잘 배워 갑니다~

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/WinningNumbers.java
> +  }
하고자 하는 일이 무엇인지 조금 더 본질적으로 생각해 보면, **포함 관계**가 아니라 **겹치는 여부**를 확인하는 것이라고 정의해야 합니다.

가령 지금은 보너스 숫자가 1개이지만, 3개로 늘어난 상황을 생각해 볼 수 있습니다. 중요한 건 추첨 번호와 보너스 번호가 겹치는지이지, 추첨 번호 안에 보너스 번호가 포함되는지는 아니라고 생각합니다.

2024-05-26 07:50 UTC, goldentrash commented on src/main/java/lotto/domain/Payment.java
> +  }
`LGTM`에 이어 `DITTO`. 잘 배워 갑니다~!

2024-05-26 11:49 UTC, closed without merging

2024-05-27 04:27 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +    return new Money(sources.stream().map((other) -> other.value).reduce(0, Integer::sum));
아뇨 이전 코드는 스트림을 한 줄로 쭉 늘어놓으셨는데, 의미 단위로 \n 구분하면 어떻겠냐는 의미였습니다.

2024-05-27 04:27 UTC, pjy1368 commented on src/main/java/lotto/domain/Money.java
> +  }
어차피 나중에 요구 사항으로 MVC 조건이 추가되긴해서 시간 될 때 시도해보시면 좋겠네요.